### ISSUE TITLE
[Feature request] Support format selection

### ISSUE THREAD

**Issue by rubensa** [sqlfluff/vscode-sqlfluff#94]
Add support to format selected text in any opened file.

_NOTE_: In my specific use case, I'd like to format some [sql changes](https://docs.liquibase.com/change-types/sql.html) and some [select queries](https://docs.liquibase.com/change-types/create-view.html) for views present in a [Liquibase](https://www.liquibase.org/) [changelog](https://docs.liquibase.com/concepts/changelogs/home.html) in [YAML format](https://docs.liquibase.com/concepts/changelogs/yaml-format.html) using the [snowflake](https://www.snowflake.com/) dialect.

**Comment by RobertOstermann** [comment]
Do you know if this is currently possible using the sqlfluff command line tool? If so I will look into this further, but if it is not possible using the command line tool then you should create an issue on the [sqlfluff](https://github.com/sqlfluff/sqlfluff) repository.

**Comment by voney** [comment]
> Do you know if this is currently possible using the sqlfluff command line tool? If so I will look into this further, but if it is not possible using the command line tool then you should create an issue on the [sqlfluff](https://github.com/sqlfluff/sqlfluff) repository.

This is possible, you'd use `-` as the path for the file and pass it in via stdin.

**Comment by RobertOstermann** [comment]
@voney Thanks for the info, that was helpful in completing this issue.

@rubensa Format Selection should be available in v2.3.5. It currently does not work if you have the `executeInTerminal` setting enabled, but otherwise should work.

**Comment by rubensa** [comment]
Great! Thanks @RobertOstermann

**Comment by RobertOstermann** [comment]
@rubensa just noticed that you wanted to be able to do this in any open file, currently it works like format document and is only available for sql files. I will look into adding formatting for any file, or maybe add a setting that lets you choose the files it can format.

**Comment by RobertOstermann** [comment]
@rubensa I have release v2.3.6 which adds the settings `sqlfluff.format.languages` and `sqlfluff.linter.languages`, you can set which languages this extension works with using those two settings.

**Comment by rubensa** [comment]
Thanks @RobertOstermann 
I'll try to check it when I have some time.

**Comment by voney** [comment]
@RobertOstermann great news, glad I could help. :)

**Comment by rubensa** [comment]
Hi @RobertOstermann 

Just checked the format selection option.

In settings I set:
```json
        "sqlfluff.format.languages": [
          "sql",
          "snowflake-sql",
          "yaml"
        ],
```
then opened a **.yml** file, selected a piece of **SQL** inside the **YAML** file and I was able to right click and select **Format Selection [Ctrl+K Ctrl+F]**.

The selection was formatted as expected!!

Only a suggestion...  Should it be possible to ad an option to keep original indentation?

I mean, in my case, the **SQL** is under a **YAML** tag like:
```yaml
- changeSet:
    id: createView-example
    author: liquibase-docs
    changes:
    - createView:
        catalogName: cat
        encoding: UTF-8
        fullDefinition: false
        path: A String
        relativeToChangelogFile: true
        remarks:  A String
        replaceIfExists:  false
        schemaName:  public
        selectQuery:
          select id, name from person where id > 10
        viewName:  v_person
```

When I select the `select id, name from person where id > 10` line and format it I get:
```yaml
- changeSet:
    id: createView-example
    author: liquibase-docs
    changes:
    - createView:
        catalogName: cat
        encoding: UTF-8
        fullDefinition: false
        path: A String
        relativeToChangelogFile: true
        remarks:  A String
        replaceIfExists:  false
        schemaName:  public
        selectQuery:
select
  id,
  name
from person where id > 10
        viewName:  v_person
```

Should It bee possible to get this instead (applying the original indentation to each resulting formatted SQL line):
```yaml
- changeSet:
    id: createView-example
    author: liquibase-docs
    changes:
    - createView:
        catalogName: cat
        encoding: UTF-8
        fullDefinition: false
        path: A String
        relativeToChangelogFile: true
        remarks:  A String
        replaceIfExists:  false
        schemaName:  public
        selectQuery:
          select
            id,
            name
          from person where id > 10
        viewName:  v_person
```
